# Generated by Django 5.2.15 on 2026-07-05 15:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='cree le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifie le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='nom')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organisations', to=settings.AUTH_USER_MODEL, verbose_name='proprietaire')),
            ],
            options={
                'verbose_name': 'organisation',
                'verbose_name_plural': 'organisations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='cree le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifie le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='nom')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='configuration')),
                ('webhook_url', models.URLField(blank=True, default='', max_length=500, verbose_name='URL webhook (defaut)')),
                ('webhook_secret', models.CharField(blank=True, default='', max_length=128, verbose_name='secret webhook')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='hub.organisation', verbose_name='organisation')),
            ],
            options={
                'verbose_name': 'profil',
                'verbose_name_plural': 'profils',
                'ordering': ['organisation__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='cree le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifie le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('connection_id', models.CharField(max_length=120, verbose_name='identifiant de connexion')),
                ('channel_type', models.CharField(choices=[('whatsapp_baileys', 'WhatsApp - Baileys (QR)'), ('whatsapp_cloud', 'WhatsApp Cloud - Meta'), ('telegram', 'Telegram'), ('email', 'Email - SMTP/IMAP')], max_length=32, verbose_name='canal')),
                ('credentials_encrypted', models.TextField(blank=True, default='', verbose_name='credentials chiffres (AES-256-GCM)')),
                ('webhook_url', models.URLField(blank=True, default='', max_length=500, verbose_name='URL webhook (surcharge)')),
                ('status', models.CharField(choices=[('disconnected', 'deconnectee'), ('connecting', 'connexion...'), ('qr_required', 'QR requis'), ('connected', 'connectee'), ('logged_out', 'session fermee'), ('error', 'erreur')], default='disconnected', max_length=20, verbose_name='statut')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='metadonnees')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='hub.profile', verbose_name='profil')),
            ],
            options={
                'verbose_name': 'connexion',
                'verbose_name_plural': 'connexions',
                'ordering': ['profile__name', 'connection_id'],
            },
        ),
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='cree le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifie le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, default='', max_length=120, verbose_name='libelle')),
                ('prefix', models.CharField(db_index=True, max_length=16, verbose_name='prefixe')),
                ('key_hash', models.CharField(max_length=128, unique=True, verbose_name='hash de la cle')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='derniere utilisation')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='revoquee le')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='hub.profile', verbose_name='profil')),
            ],
            options={
                'verbose_name': 'cle API',
                'verbose_name_plural': 'cles API',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.UniqueConstraint(fields=('organisation', 'name'), name='uniq_profil_par_organisation'),
        ),
        migrations.AddConstraint(
            model_name='connection',
            constraint=models.UniqueConstraint(fields=('profile', 'connection_id'), name='uniq_connexion_par_profil'),
        ),
    ]
